### ISSUE TITLE
Latest Nightly crashing

### ISSUE THREAD

**Issue by NikunjKhangwal** [abdallahmehiz/mpvKt#48]
I wanted to try out the precise seek changes but the latest nightly is crashing as soon as video is played.

[mpvKt_logs.txt](https://github.com/user-attachments/files/16910759/mpvKt_logs.txt)

**Comment by abdallahmehiz** [comment]
the crash logs is empty

**Comment by NikunjKhangwal** [comment]
By empty you mean there's no text at all or no relevant information? It's showing a huge list for me.
This is what i got from app itself.

**Comment by abdallahmehiz** [comment]
Lol nvm me, I didn't check it properly.
does it still happen? the crash i mean.

**Comment by NikunjKhangwal** [comment]
Yup, still happening

**Comment by abdallahmehiz** [comment]
I can't replicate it, if possible, can you provide me the video that's causing the crash?

**Comment by NikunjKhangwal** [comment]
I'm on limited internet now, will do in few hours.

**Comment by NikunjKhangwal** [comment]
Here you go:
https://drive.google.com/file/d/1mE0kQkovrp7L0zcoOjWUZu-Vilm2rFxc/view?usp=sharing

**Comment by abdallahmehiz** [comment]
Looks like it's crashing cause the first chapter doesn't start on 0
`Segment(name=Opening Theme, start=0.014, color=Color(0.0, 0.0, 0.0, 0.0, None))`

**Comment by NikunjKhangwal** [comment]
Weird thing is it doesn't crash in stable version. I guess any change made later broke it.

**Comment by abdallahmehiz** [comment]
lol i committed unfinished changes... sloppy work lemme fix it

**Comment by NikunjKhangwal** [comment]
No problem. Midnight coding, I understand. I've been looking for a better open source video player for a long time and I am very interested in this app. I'll keep testing nightly versions every once in a while and report stuff. Keep up the nice work :)

**Comment by NikunjKhangwal** [comment]
Hello There, it's still crashing but a different log this time.

`      App version: 0.1.4-185 (c1e544b)
Android version: 14 (34)
Device brand: Redmi
Device manufacturer: Xiaomi
Device model: Redmi 9 (lancelot)
MPV version: v0.38.0-743-gad7976c33e
ffmpeg version: 0b6d7cd9d9
libplacebo version: v7.349.0 (v7.349.0-9-gefb89342)
      
      Exception:
      java.lang.RuntimeException: Unable to start activity ComponentInfo{live.mehiz.mpvkt.preview/live.mehiz.mpvkt.ui.player.PlayerActivity}: java.io.FileNotFoundException: /data/user/0/live.mehiz.mpvkt.preview/files/mpv.conf: open failed: ENOENT (No such file or directory)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8243)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.io.FileNotFoundException: /data/user/0/live.mehiz.mpvkt.preview/files/mpv.conf: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at kotlin.uuid.UuidKt.forEachLine(SourceFile:12)
	at live.mehiz.mpvkt.ui.player.MPVView.initOptions(SourceFile:922)
	at is.xyz.mpv.BaseMPVView.initialize(Unknown Source:49)
	at live.mehiz.mpvkt.ui.player.PlayerActivity.onCreate(SourceFile:275)
	at android.app.Activity.performCreate(Activity.java:8627)
	at android.app.Activity.performCreate(Activity.java:8605)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1460)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3804)
	... 12 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8129)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 21 more

      
      Logcat:
      --------- beginning of main
09-08 19:41:56.359  6849  6849 I z.mpvkt.preview: Using CollectorTypeCC GC.
09-08 19:41:56.376  6849  6849 E z.mpvkt.preview: Not starting debugger since process cannot load the jdwp agent.
09-08 19:41:56.437  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10614; state: ENABLED
09-08 19:41:56.437  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10614; state: ENABLED
09-08 19:41:56.449  6849  6849 D nativeloader: Configuring clns-4 for other apk /data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/lib/arm64:/data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt.preview
09-08 19:41:56.477  6849  6849 V GraphicsEnvironment: Currently set values for:
09-08 19:41:56.477  6849  6849 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
09-08 19:41:56.477  6849  6849 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
09-08 19:41:56.478  6849  6849 V GraphicsEnvironment: ANGLE GameManagerService for live.mehiz.mpvkt.preview: false
09-08 19:41:56.478  6849  6849 V GraphicsEnvironment: live.mehiz.mpvkt.preview is not listed in per-application setting
09-08 19:41:56.478  6849  6849 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
09-08 19:41:56.556  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10614; state: DISABLED
09-08 19:41:56.557  6849  6849 W OpenGLRenderer: Unknown dataspace 0
09-08 19:41:56.689  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 289878283; UID 10614; state: ENABLED
09-08 19:41:56.778  6849 14754 E OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
09-08 19:41:56.778  6849 14754 W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
09-08 19:41:56.792  6849 14773 I Gralloc4: Adding additional valid usage bits: 0x0
09-08 19:41:56.794  6849 14773 E ion     : ioctl c0044901 failed with code -1: Invalid argument
09-08 19:41:57.610  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:41:57.610  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:41:57.627  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10614; state: ENABLED
09-08 19:42:02.270  6849 14796 D ProfileInstaller: Installing profile for live.mehiz.mpvkt.preview
09-08 19:42:03.650  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:42:03.650  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:42:04.451  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@aa97327
09-08 19:42:10.130  6849 14746 W z.mpvkt.preview: Cleared Reference was only reachable from finalizer (only reported once)
09-08 19:42:11.059  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:42:11.059  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:42:11.645  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@6da146d
09-08 19:42:37.283  6849  6849 D SCViewSupport: screenshot.scroll_capture_delay = 60
09-08 19:42:45.314  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:42:45.314  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:15.142  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:43:15.142  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:16.083  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@ae09f03
09-08 19:43:22.681  6849  6849 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10614; state: ENABLED
09-08 19:43:22.683  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:43:22.683  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:25.176  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:43:25.176  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:25.224  6849  6849 D Compose Focus: Owner FocusChanged(true)
09-08 19:43:25.239  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:27049770: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:25.239  6849  6849 D InsetsController: show(ime(), fromIme=false)
09-08 19:43:25.239  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:27049770: onFailed at PHASE_CLIENT_REQUEST_IME_SHOW
09-08 19:43:25.284  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:dfb9e640: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:25.285  6849  6849 D InputMethodManager: showSoftInput() view=androidx.compose.ui.platform.AndroidComposeView{94a451c VFED..... .F...... 0,0-880,559 aid=1073741827} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:25.358  6849  6849 D InsetsController: show(ime(), fromIme=true)
09-08 19:43:25.478  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:dfb9e640: onShown
09-08 19:43:26.689  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@27984832 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@d8e0c68
09-08 19:43:26.689  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@8c052fc
09-08 19:43:26.695  6849 14754 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072e6f46380 (UnprojectedRipple) with handle 0xb4000071d6f23850
09-08 19:43:26.708  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:521c6b56: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
09-08 19:43:26.708  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:521c6b56: onFailed at PHASE_CLIENT_VIEW_SERVED
09-08 19:43:26.731  6849  6849 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 27984832
09-08 19:43:26.735  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:74decb7c: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
09-08 19:43:27.352  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:43:27.352  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:27.403  6849  6849 D Compose Focus: Owner FocusChanged(true)
09-08 19:43:27.413  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:1b4169e8: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:27.413  6849  6849 D InsetsController: show(ime(), fromIme=false)
09-08 19:43:27.413  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:1b4169e8: onFailed at PHASE_CLIENT_REQUEST_IME_SHOW
09-08 19:43:27.459  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:c678f776: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:27.459  6849  6849 D InputMethodManager: showSoftInput() view=androidx.compose.ui.platform.AndroidComposeView{1b490dc VFED..... .F...... 0,0-880,559 aid=1073741828} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
09-08 19:43:27.464  6849 14748 W System  : A resource failed to call release. 
09-08 19:43:27.514  6849  6849 D InsetsController: show(ime(), fromIme=true)
09-08 19:43:27.621  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:c678f776: onShown
09-08 19:43:28.162  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@27984832 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@417503c
09-08 19:43:28.162  6849  6849 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@25efebc
09-08 19:43:28.171  6849 14754 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072e6f1b2b0 (UnprojectedRipple) with handle 0xb4000071d6ed75c0
09-08 19:43:28.183  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:540cd7a9: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
09-08 19:43:28.183  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:540cd7a9: onFailed at PHASE_CLIENT_VIEW_SERVED
09-08 19:43:28.199  6849  6849 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 27984832
09-08 19:43:28.200  6849  6849 I ImeTracker: live.mehiz.mpvkt.preview:d9ad6fb: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
09-08 19:43:34.844  6849 14754 D OpenGLRenderer: endAllActiveAnimators on 0xb4000072e6eeae30 (UnprojectedRipple) with handle 0xb4000071d6f2c400
09-08 19:43:38.407  6849  6849 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-08 19:43:38.407  6849  6849 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-08 19:43:43.795  6849  6849 W Choreographer: Frame time is 0.071621 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
09-08 19:43:52.980  6849  6849 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
09-08 19:43:53.056  6849  6849 W mpv     : Copied asset file: subfont.ttf
09-08 19:43:53.059  6849  6849 W mpv     : Copied asset file: cacert.pem
09-08 19:43:53.152  6849 14784 W DocumentFile: Failed query: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
09-08 19:43:53.152  6849 14784 E PlayerActivity: Couldn't copy fonts to application directory: User hasn't set any fonts directory
09-08 19:43:53.212  6849  6849 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-08 19:43:53.212  6849  6849 E AndroidRuntime: FATAL EXCEPTION: main
09-08 19:43:53.212  6849  6849 E AndroidRuntime: Process: live.mehiz.mpvkt.preview, PID: 6849
09-08 19:43:53.212  6849  6849 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{live.mehiz.mpvkt.preview/live.mehiz.mpvkt.ui.player.PlayerActivity}: java.io.FileNotFoundException: /data/user/0/live.mehiz.mpvkt.preview/files/mpv.conf: open failed: ENOENT (No such file or directory)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8243)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: Caused by: java.io.FileNotFoundException: /data/user/0/live.mehiz.mpvkt.preview/files/mpv.conf: open failed: ENOENT (No such file or directory)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:574)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at kotlin.uuid.UuidKt.forEachLine(SourceFile:12)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at live.mehiz.mpvkt.ui.player.MPVView.initOptions(SourceFile:922)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at is.xyz.mpv.BaseMPVView.initialize(Unknown Source:49)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at live.mehiz.mpvkt.ui.player.PlayerActivity.onCreate(SourceFile:275)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8627)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8605)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1460)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3804)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	... 12 more
09-08 19:43:53.212  6849  6849 E AndroidRuntime: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.Linux.open(Native Method)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8129)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	at libcore.io.IoBridge.open(IoBridge.java:560)
09-08 19:43:53.212  6849  6849 E AndroidRuntime: 	... 21 more
09-08 19:43:53.222  6849  6849 I z.mpvkt.preview: System.exit called, status: 0
09-08 19:43:53.222  6849  6849 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
09-08 19:43:53.299  6846  6846 I z.mpvkt.preview: Using CollectorTypeCC GC.
09-08 19:43:53.303  6846  6846 E z.mpvkt.preview: Not starting debugger since process cannot load the jdwp agent.
09-08 19:43:53.342  6846  6846 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10614; state: ENABLED
09-08 19:43:53.343  6846  6846 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10614; state: ENABLED
09-08 19:43:53.356  6846  6846 D nativeloader: Configuring clns-4 for other apk /data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/lib/arm64:/data/app/~~afcr35OgrYlu1C05hGqHwQ==/live.mehiz.mpvkt.preview-1FNmE_8TamL80chJdjILqQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt.preview
09-08 19:43:53.363  6846  6846 V GraphicsEnvironment: Currently set values for:
09-08 19:43:53.363  6846  6846 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
09-08 19:43:53.363  6846  6846 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
09-08 19:43:53.364  6846  6846 V GraphicsEnvironment: ANGLE GameManagerService for live.mehiz.mpvkt.preview: false
09-08 19:43:53.364  6846  6846 V GraphicsEnvironment: live.mehiz.mpvkt.preview is not listed in per-application setting
09-08 19:43:53.364  6846  6846 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
`

**Comment by NikunjKhangwal** [comment]
Hello!
Just tried the latest nightly, it's still crashing but now for every video not just the ones with chapters.

[mpvKt_logs.txt](https://github.com/user-attachments/files/16922542/mpvKt_logs.txt)

**Comment by NikunjKhangwal** [comment]
Another crash, i guess you'll have to take a look again. 😶
[mpvKt_logs.txt](https://github.com/user-attachments/files/16922681/mpvKt_logs.txt)

**Comment by abdallahmehiz** [comment]
You're on preview -177... That's before the fix...

**Comment by NikunjKhangwal** [comment]
I used this action which references the commit 8a49c86:
https://github.com/abdallahmehiz/mpvKt/actions/runs/10760669170

This is not the correct build?

**Comment by NikunjKhangwal** [comment]
I probably downloaded the wrong nightly build, my bad. You're right, it's fixed now.
